// actionTypes.ts
export const ADD_ADJUSTMENT = "ADD_ADJUSTMENT";
export const FIND_ONE_ADJUSTMENT = "FIND_ONE_ADJUSTMENT";
export const REMOVE_ADJUSTMENT = "REMOVE_ADJUSTMENT";
export const UPDATE_ADJUSTMENT = "UPDATE_ADJUSTMENT";
// actionTypes.ts
export const FETCH_ADJUSTMENTS_REQUEST = "FETCH_ADJUSTMENTS_REQUEST";
export const FETCH_ADJUSTMENTS_SUCCESS = "FETCH_ADJUSTMENTS_SUCCESS";
export const FETCH_ADJUSTMENTS_FAILURE = "FETCH_ADJUSTMENTS_FAILURE";
export const UPLOAD_ADJUSTMENTS = `ADJUSTMENTS/UPLOAD/REQUEST`
